apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spire-demo
  region: us-east-1
  version: "1.28"
vpc:
  id: vpc-0e09482bf6c567464
  subnets:
    public:
      us-east-1a:
        id: subnet-09ed6955ae85f5583
      us-east-1b:
        id: subnet-08a698c7c26d608b4
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: false
