apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spire-demo
  region: us-east-1
  version: "1.28"
nodeGroups:
  - name: ng-1
    instanceType: t3.medium
    desiredCapacity: 2
    ssh:
      allow: false
