apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: default
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      spiffe.io/spire-managed-identity: "true"
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: spiffe-csi-proxy
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/spiffe-csi-proxy/sa/spiffe-csi-proxy"
  workloadSelectorTemplates:
    - k8s:ns:spiffe-csi-proxy
    - k8s:sa:spiffe-csi-proxy
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: ingressgw
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/istio-system/sa/istio-ingressgateway"
  workloadSelectorTemplates:
    - k8s:ns:spiffe-csi-proxy
    - k8s:sa:spiffe-csi-proxy
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: ingressgw-app1
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/istio-system/sa/app1"
  workloadSelectorTemplates:
    - k8s:ns:spiffe-csi-proxy
    - k8s:sa:spiffe-csi-proxy
  dnsNameTemplates:
    - app1.example.org
---
apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: ingressgw-app2
spec:
  spiffeIDTemplate: "spiffe://{{ .TrustDomain }}/ns/istio-system/sa/app2"
  workloadSelectorTemplates:
    - k8s:ns:spiffe-csi-proxy
    - k8s:sa:spiffe-csi-proxy
  dnsNameTemplates:
    - app2.example.org