apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  namespace: istio-system
spec:
  profile: default
  meshConfig:
    trustDomain: example.org
  values:
    global:
    sidecarInjectorWebhook:
      templates:
        spire: |
          spec:
            containers:
            - name: istio-proxy
              volumeMounts:
              - name: credential-socket
                mountPath: /run/secrets/credential-uds
                readOnly: true
            volumes:
              - name: credential-socket
                csi:
                  driver: "csi.spiffe.io"
                  readOnly: true
    pilot:
      env:
        ENABLE_SPIFFE_SDS: "true"
  components:
    pilot:
      k8s:
        env:
          - name: ENABLE_SPIFFE_SDS
            value: "true"
          - name: PILOT_ENABLE_SDS_SERVER
            value: "true"
          - name: AUTO_RELOAD_PLUGIN_CERTS
            value: "true"
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        label:
          istio: ingressgateway
        k8s:
          podAnnotations:
            proxy.istio.io/config: |
              {
                "metadata": {
                  "CREDENTIAL_NAME": "true"
                }
              }
          overlays:
            - apiVersion: apps/v1
              kind: Deployment
              name: istio-ingressgateway
              patches:
                - path: spec.template.spec.volumes.[name:credential-socket]
                  value:
                    name: credential-socket
                    csi:
                      driver: "csi.spiffe.io"
                      readOnly: true
                - path: spec.template.spec.containers.[name:istio-proxy].volumeMounts.[name:credential-socket]
                  value:
                    name: credential-socket
                    mountPath: "/run/secrets/credential-uds"
                    readOnly: true
                - path: spec.template.spec.volumes.[name:ingressgateway-certs]
                  value:
                    name: ingressgateway-certs
                    csi:
                      driver: "ingress.csi.spiffe.io"
                      readOnly: true
                - path: spec.template.spec.containers.[name:istio-proxy].volumeMounts.[name:ingressgateway-certs]
                  value:
                    name: ingressgateway-certs
                    mountPath: "/etc/istio/ingressgateway-certs"
                    readOnly: true