kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: spire-demo
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 30000
  - containerPort: 30443
    hostPort: 30443
