apiVersion: v1
kind: ServiceAccount
metadata:
  name: svid-secret-sync
  namespace: istio-system
---
# RBAC for managing secrets in istio-system namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-writer
  namespace: istio-system
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: svid-secret-writer
  namespace: istio-system
subjects:
  - kind: ServiceAccount
    name: svid-secret-sync
    namespace: istio-system
roleRef:
  kind: Role
  name: secret-writer
  apiGroup: rbac.authorization.k8s.io