apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: spiffe-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
        spiffe.io/spire-managed-identity: "true"
    spec:
      serviceAccountName: client-sa
      containers:
        - name: client
          image: fengyu225/spiffe-demo-client:v0.0.1
          imagePullPolicy: Always
          command:
            - sleep
            - infinity
#          args:
#            - --server-url=https://server-service:8443
#            - --cert-dir=/run/spiffe/certs
          volumeMounts:
            - name: spiffe-certs
              mountPath: /run/spiffe/certs
        - name: spiffe-helper
          image: docker.io/fengyu225/spiffe-helper:v0.0.1
          imagePullPolicy: Always
          args:
            - -config
            - /etc/spiffe-helper/helper.conf
          volumeMounts:
            - name: spiffe-helper-config
              mountPath: /etc/spiffe-helper
            - name: spire-agent-socket
              mountPath: /run/spire/agent-sockets
              readOnly: true
            - name: spiffe-certs
              mountPath: /run/spiffe/certs
      volumes:
        - name: spire-agent-socket
          hostPath:
            path: /run/spire/agent-sockets
            type: Directory
        - name: spiffe-helper-config
          configMap:
            name: client-spiffe-helper-config
        - name: spiffe-certs
          emptyDir: {}