apiVersion: v1
kind: ServiceAccount
metadata:
  name: ingress-svid-csi-driver
  namespace: istio-system
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-svid-csi-driver
rules:
  - apiGroups: [""]
    resources: ["nodes"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: ingress-svid-csi-driver
subjects:
  - kind: ServiceAccount
    name: ingress-svid-csi-driver
    namespace: istio-system
roleRef:
  kind: ClusterRole
  name: ingress-svid-csi-driver
  apiGroup: rbac.authorization.k8s.io