apiVersion: v1
kind: ConfigMap
metadata:
  name: spire-server
  namespace: spire
data:
  server.conf: |
    server {
      bind_address = "0.0.0.0"
      bind_port = "8081"
      trust_domain = "example.org"
      data_dir = "/run/spire/server/data"
      log_level = "DEBUG"
      default_x509_svid_ttl = "24h"
      ca_ttl = "48h"
      ca_subject = {
        country = ["US"]
        organization = ["Example Organization"]
        common_name = "example.org"
      }
      ca_key_type = "rsa-2048"
      federation {
        bundle_endpoint {
          address = "0.0.0.0"
          port = 8443
        }
      }
    }

    plugins {
      DataStore "sql" {
        plugin_data {
          database_type = "postgres"
          connection_string = "postgresql://spire_admin:AVNS_5ZG_b_MaTCmqlZBDld_@db-postgresql-sfo2-16385-do-user-10570456-0.i.db.ondigitalocean.com:25060/spiredb?sslmode=require"
        }
      }    

      NodeAttestor "k8s_psat" {
        plugin_data {
          clusters = {
            "spire-demo" = {
              service_account_allow_list = ["spire:spire-agent"]
            }
          }
        }
      }
    
      # UpstreamAuthority "vault" {
      #   plugin_data {
      #     # Use the docker container name that will be accessible from Kind
      #     vault_addr = "https://vault:8200"
      #     insecure_skip_verify = true
      #     pki_mount_point = "pki_root"
      #     ca_cert_path = "/spire/vault/ca.crt"
      #     cert_auth {
      #       cert_auth_mount_point = "cert"
      #       client_cert_path = "/spire/vault/client.crt"
      #       client_key_path = "/spire/vault/client.key"
      #     }
      #   }
      # }    
    
      KeyManager "memory" {
      }
   
      Notifier "k8sbundle" {
        plugin_data {
          namespace = "spire"
        }
      }
    }

    health_checks {
      listener_enabled = true
      bind_address = "0.0.0.0"
      bind_port = "8080"
      live_path = "/live"
      ready_path = "/ready"
    }