apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: "csi.spiffe.proxy"
spec:
  attachRequired: false
  podInfoOnMount: true
  fsGroupPolicy: None
  volumeLifecycleModes:
    - Ephemeral
  tokenRequests:
    - audience: "spiffe://example.org"
      expirationSeconds: 3600
  requiresRepublish: true